[project]
name = 'Viral-Content-Authenticity-Verification-Bureau'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.genuine-fake-authenticity-detector]
path = 'contracts/genuine-fake-authenticity-detector.clar'
clarity_version = 3
epoch = 'latest'

[contracts.spontaneous-virality-predictive-analytics]
path = 'contracts/spontaneous-virality-predictive-analytics.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
